FM2-311:Refactor to remove BaseServiceRequestTranslatorImpl
openmrs/openmrs-module-fhir2 pull request #304
Opened 2020-10-30 06:40 UTC by gitcliff

link:https://issues.openmrs.org/browse/FM2-311

2020-11-03 16:34 UTC, varung-31 requested changes

2020-11-03 16:34 UTC, varung-31 commented on api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ServiceRequestTranslatorImpl.java
> +				break;
Please add tab indentation

2020-11-03 16:34 UTC, varung-31 commented on api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/BaseServiceRequestTranslatorImpl.java
>  public abstract class BaseServiceRequestTranslatorImpl {
Since this class is not being used at all, why not delete it completely?

2020-11-11 19:23 UTC, varung-31 approved these changes

2020-11-17 15:23 UTC, ibacher approved these changes

2020-11-17 15:23 UTC, merged

2020-11-17 15:24 UTC, ibacher commented
Thanks @gitcliff!