FM2-366: Implement Encounter.period mapping
openmrs/openmrs-module-fhir2 pull request #339
Opened 2021-03-24 20:17 UTC by pmanko

## Description of what I changed
Adding the functionality to map between:
- OpenMRS Encounter `encounterDatetime` and FHIR `Encounter.period`
- OpenMRS Visit `startDatetime` and `stopDatetime` and FHIR `Encounter.period`

## Issue I worked on

see https://issues.openmrs.org/browse/FM2-366

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

2021-03-25 04:46 UTC, HerbertYiga commented on api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/VisitTranslatorImplTest.java
> +
@pmanko  thanks for working on this,add a ticket id to your commit and you can also remove the spaces from your code

2021-03-25 04:47 UTC, HerbertYiga commented on api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/EncounterPeriodTranslatorImpl.java
> +
remove space

2021-03-25 04:48 UTC, HerbertYiga commented on api/src/main/java/org/openmrs/module/fhir2/api/translators/EncounterPeriodTranslator.java
> +
remove spaces

2021-03-25 04:49 UTC, HerbertYiga commented on api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/VisitPeriodTranslatorImpl.java
> +
remove space

2021-03-25 04:49 UTC, HerbertYiga commented on api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/EncounterPeriodTranslatorImplTest.java
> +
remove space

2021-03-25 04:51 UTC, HerbertYiga commented on api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/EncounterPeriodTranslatorImplTest.java
> +		assertThat(result, equalTo(encounterDate));
thanks i was looking for this line ie testing that actually the dates are equal

2021-03-25 04:52 UTC, HerbertYiga commented on api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/VisitTranslatorImplTest.java
> +
remove space

2021-03-25 12:40 UTC, ibacher requested changes

2021-03-25 12:40 UTC, ibacher commented on api/src/main/java/org/openmrs/module/fhir2/api/translators/EncounterPeriodTranslator.java
> +public interface EncounterPeriodTranslator extends ToFhirTranslator<Date, Period>, OpenmrsFhirTranslator<Date, Period> {
Wouldn't it be better to structure this as an interface that translates between an OpenMRS type and a date? That way, we only need a single interface (`EncounterPeriodTranslator`) that has two specialisations (one for `Encounter`, one for `Visit`) and we don't have to do weird things like returning `Pairs`

2021-03-25 12:40 UTC, ibacher commented on api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/EncounterTranslatorImplTest.java
> +import org.hl7.fhir.r4.model.*;
Please don't use `*` imports. This is an OpenMRS convention.

2021-03-25 12:40 UTC, ibacher commented on omod/pom.xml
> +	</profiles>
This is maybe something we should discuss separately from this PR?

2021-03-25 12:40 UTC, ibacher commented on pom.xml
> +        </profile>
Ditto. PS I think I separately disabled `test-jar`s in [this commit](https://github.com/openmrs/openmrs-module-fhir2/commit/bd57419d45feadab98554b338eb4b3b8c0fdeba2).

2021-04-13 15:42 UTC, ibacher commented
@pmanko Any update on this?

2021-04-20 15:10 UTC, ibacher approved these changes

2021-04-20 15:10 UTC, merged