FM2-401: Added support for $lastn-encounters in R3
openmrs/openmrs-module-fhir2 pull request #357
Opened 2021-07-01 22:18 UTC by Medhavi-16

## Description of what I changed

## Issue I worked on

see https://issues.openmrs.org/browse/FM2-401

## Checklist: I completed these to help reviewers :)

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

2021-07-01 22:19 UTC, Medhavi-16 commented
@ibacher @varung-31 PTAL.

2021-07-03 19:49 UTC, varung-31 requested changes

2021-07-03 19:49 UTC, varung-31 commented on api/src/main/java/org/openmrs/module/fhir2/providers/r3/ObservationFhirResourceProvider.java
> +	@Operation(name = "lastn-encounters", idempotent = true, type = org.hl7.fhir.r4.model.Observation.class)
We should be using the Observation model for R3.

2021-07-04 17:56 UTC, Medhavi-16 commented
@varung-31 @ibacher PTAL.

2021-07-06 16:05 UTC, varung-31 approved these changes
LGTM!

2021-07-08 15:37 UTC, merged