FM2-418: Support for type-level $everything operation on Patients
openmrs/openmrs-module-fhir2 pull request #363
Opened 2021-07-27 10:50 UTC by Medhavi-16

## Description of what I changed

## Issue I worked on

see https://issues.openmrs.org/browse/FM2-418

## Checklist: I completed these to help reviewers :)

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

2021-07-27 11:09 UTC, Medhavi-16 commented
@ibacher @varung-31 PTAL.

2021-07-27 17:29 UTC, varung-31 requested changes
Great work @Medhavi-16! Some minor comments and it should be good.

2021-07-27 17:29 UTC, varung-31 commented on api/src/main/java/org/openmrs/module/fhir2/api/FhirPatientService.java
> +	IBundleProvider getPatientEverythingType();
We could have overloaded methods.
```suggestion
	IBundleProvider getPatientEverything();
```

2021-07-27 17:29 UTC, varung-31 commented on api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirPatientServiceImpl.java
> +	private void getEverythingReverseInclude(SearchParameterMap theParams) {
`getEverythingReverseInclude` feels like the method returns us something.
A better name should be `populateEverythingOperationParams`

2021-07-27 17:29 UTC, varung-31 commented on omod/src/test/java/org/openmrs/module/fhir2/providers/r4/PatientFhirResourceProviderWebTest.java
> +		MatcherAssert.assertThat(response.getContentType(), equalTo(FhirMediaTypes.JSON.toString()));
```suggestion
		assertThat(response, isOk());
		assertThat(response.getContentType(), equalTo(FhirMediaTypes.JSON.toString()));
```

2021-07-27 19:35 UTC, Medhavi-16 commented on omod/src/test/java/org/openmrs/module/fhir2/providers/r4/PatientFhirResourceProviderWebTest.java
> +		MatcherAssert.assertThat(response.getContentType(), equalTo(FhirMediaTypes.JSON.toString()));
@ibacher @varung-31 PTAL

2021-08-02 15:53 UTC, varung-31 commented
LGTM! @ibacher Do you have anything to add?

2021-08-02 19:51 UTC, ibacher commented on omod/src/test/java/org/openmrs/module/fhir2/providers/r4/PatientFhirResourceProviderWebTest.java
> +		MatcherAssert.assertThat(response.getContentType(), equalTo(FhirMediaTypes.JSON.toString()));
@Medhavi-16 Has this been addressed?

2021-08-02 19:53 UTC, ibacher commented
@Medhavi-16 I had to do some Git gymnastic to create a point release for this module. Would you be able to fix the resulting conflicts? Thanks! Otherwise, this LGTM.

2021-08-02 19:58 UTC, Medhavi-16 commented
> @Medhavi-16 I had to do some Git gymnastic to create a point release for this module. Would you be able to fix the resulting conflicts? Thanks! Otherwise, this LGTM.

Yes, @ibacher I'll resolve the conflicts.

2021-08-03 13:02 UTC, Medhavi-16 commented
@ibacher @varung-31 PTAL.

2021-08-03 14:31 UTC, ibacher approved these changes

2021-08-03 14:31 UTC, ibacher commented
Thanks @Medhavi-16!

2021-08-03 14:31 UTC, merged