FM2-481: Clean up parameter passing for Task Service class search method
openmrs/openmrs-module-fhir2 pull request #442
Opened 2022-11-06 07:48 UTC by mherman22

## Description of what I changed

    Added TaskSearchParams class that extends the BaseResourceSearchParams.
    Refactor all provider classes (r3 and r4).
    Ensure all tests are passing

## Issue I worked on

see  https://issues.openmrs.org/browse/FM2-481

## Checklist: I completed these to help reviewers :)

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

2023-05-30 12:03 UTC, ibacher requested changes
Thanks @mherman22! A couple of quick adjustments and I think this should be g2g.

2023-05-30 22:46 UTC, mherman22 commented on api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirTaskServiceImpl.java
> -	/**
Done

2023-05-30 22:46 UTC, mherman22 commented on api/src/main/java/org/openmrs/module/fhir2/api/FhirTaskService.java
> -	/**
Done

2023-06-30 17:24 UTC, ibacher approved these changes

2023-06-30 17:24 UTC, merged