FM2-636: Enhancements in Existing FHIR Task Resource (#5)
openmrs/openmrs-module-fhir2 pull request #539
Opened 2024-04-10 04:34 UTC by kalai-tw

## Description of what I changed

Made below Changes to FHIR Task Entity Model:

- Added new columns to `fhir_task`:
  - `task_code`: to determine task type
  - `execution_start_time`: start time of execution
  - `execution_end_time`: end time of execution
  - `comment`: comment to task

- Added a new table `fhir_part_of_reference` to support subtasks to a parent task.

## Issue I worked on
see https://issues.openmrs.org/browse/FM2-636
talk thread ref https://talk.openmrs.org/t/contribution-to-fhir-task/42015

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

- [x] I have **added tests** to cover my changes.

- [x] I ran `mvn clean package` right before creating this pull request 

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

2024-04-10 16:03 UTC, ibacher requested changes
Thanks! This mostly LGTM. It would be good to add at least one integration test that verifies some of the changes here.

Also is there no need to be able to _search_ for tasks by these attributes? I would imagine, for example, that being able to search by code would be very useful.

2024-04-10 16:03 UTC, ibacher commented on api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/TaskTranslatorImplTest.java
> +		assertThat(result.getCode(), CoreMatchers.equalTo(fhirObject));
```suggestion
		FhirTask task = new FhirTask();
		Concept openmrsObject = new Concept();
		CodeableConcept fhirObject = newCodeableConcept();
		when(conceptTranslator.toFhirResource(openmrsObject)).thenReturn(fhirObject);
		task.setTaskCode(openmrsObject);
		
		Task result = taskTranslator.toFhirResource(task);
		
		assertThat(result.getCode(), CoreMatchers.notNullValue());
		assertThat(result.getCode(), CoreMatchers.equalTo(fhirObject));
```

General rule here is to break things (visually) into: setup / execution / assertions. It makes the tests easier to tell what they do at a glance. This formatting should be adopted for all the tests in this file.

2024-04-17 19:07 UTC, kalai-tw commented on api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/TaskTranslatorImplTest.java
> +	public void toOpenmrsType_shouldupdateExecutionTimeOnExistingTask() {
Fixed

2024-04-17 19:12 UTC, kalai-tw commented
Hello @ibacher ! Thanksa for the feedbacks !

Yeap ! We would need Search By Code & Search By For Reference . Have added them in this new commit !

Also, Have Added the Integrations Tests now :)

2024-04-23 22:56 UTC, dkayiwa commented
@kalai-tw do you mind looking into the above failing build?

2024-05-09 15:46 UTC, ibacher approved these changes

2024-05-16 19:01 UTC, ibacher commented
@kalai-tw Could you rebase this branch on master, since we've committed the fix for the test?

2024-05-17 05:28 UTC, kalai-tw commented
thanq @ibacher rebased & now the PR pipeline looks green ! can u help on squash & merging the same ?

2024-05-20 18:03 UTC, merged