(fix) Void old patient names
openmrs/openmrs-module-fhir2 pull request #546
Opened 2024-07-23 11:18 UTC by icrc-jofrancisco

## Description of what I changed

### Problem
When updating a patient's name using the FHIR endpoint, a new person_name entry is created in the database instead of voiding the existing one and creating a new entry. This results in multiple active names for a single patient, which is incorrect and leads to data inconsistencies. Additionally, OpenMRS does not consider more than one name and always picks the first one, so users cannot see any changes in the **UI.**

### Solution
This fix addresses the problem by:

- Voiding the old person_name entries with the appropriate voided date and voided reason.
- Adding the new patient name as a fresh entry.

By implementing this approach, we ensure that the system can track changes to patient names over time, allowing for analysis of when names were changed and what the previous values were. Moreover, it ensures that the UI reflects the latest changes accurately, as only the active name will be considered.

## Issue I worked on

see https://issues.openmrs.org/browse/FM2-

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

2024-07-23 12:45 UTC, ibacher commented
Functionally, it's incorrect to assume a patient should only have one name. We can, however, try voiding any names that are not in the list. (The UI defaults to the preferred name for a client, but that doesn't mean additional names are not important).

2024-07-23 14:48 UTC, icrc-jofrancisco commented
> Functionally, it's incorrect to assume a patient should only have one name. We can, however, try voiding any names that are not in the list. (The UI defaults to the preferred name for a client, but that doesn't mean additional names are not important).

Hey @ibacher , thanks for the feddback.

You're right. I'm trying to implement a logic to update the name instead of setting the others to voided.
But right now I can't figure out which name should be updated, because we only get a list of all names...

I'm still investigating another possible solution, which is why I put the PR in draft. 
Anyway, thanks for the feedback!

2024-10-11 13:39 UTC, delphinepas commented
@denniskigen @ibacher would it be possible for you to review this PR ? Thank you cc @icrc-jofrancisco @icrc-fdeniger @gracepotma

2024-10-15 12:50 UTC, ibacher requested changes

2024-10-15 12:50 UTC, ibacher commented on api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PatientTranslatorImpl.java
> +				existingName = currentPatient.getPersonName();
This behaviour still strikes me as incorrectly assuming that a patient has only a single name...

2024-10-15 12:50 UTC, ibacher commented on api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PatientTranslatorImpl.java
> +				existingName = currentPatient.getPersonName();
I'm on board with matching existing names based on UUIDs, but I'm not sold that this is a good idea.

2024-12-03 20:01 UTC, ibacher approved these changes

2024-12-03 20:02 UTC, merged